apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: priyanshu0811/backend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-db-config 
                  key: DB_PORT
            # - name: POSTGRES_DB
            #   valueFrom:
            #     configMapKeyRef:
            #       name: postgres-db-config 
            #       key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets 
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets 
                  key: POSTGRES_PASSWORD
          volumeMounts:
          - name: host-proc
            mountPath: /host/proc
            readOnly: true
          - name: host-etc
            mountPath: /host/etc
            readOnly: true
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory
      - name: host-etc
        hostPath:
          path: /etc
          type: Directory
      
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000         
      targetPort: 5000   
  type: ClusterIP
