apiVersion: v1
kind: Secret
metadata: 
  name: postgres-db-secrets 
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # Base64 for 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 for 'password'
